"""Governed synthetic supplier expansion profiles for portfolio realism.

The functions in this module append synthetic demonstration rows only. They do
not change scoring, eligibility, allocation, scenario, export, or approval
logic. All records remain explicitly non-audited demonstration evidence.
"""

from __future__ import annotations

import pandas as pd


def _append(base: pd.DataFrame, rows: list[dict]) -> pd.DataFrame:
    """Append rows while preserving dataframe attributes."""
    result = pd.concat([base, pd.DataFrame(rows)], ignore_index=True, sort=False)
    result.attrs.update(base.attrs)
    return result


def expand_general_packaging(base: pd.DataFrame) -> pd.DataFrame:
    rows = [
        {
            "Supplier": "EcoForm Packaging Solutions",
            "Quoted Unit Price USD": 0.40,
            "Currency": "USD",
            "Unit": "piece",
            "MOQ": 25000,
            "Lead Time Days": 21,
            "Payment Terms": "Net 45",
            "Incoterms": "DDP",
            "OTIF %": 92,
            "Quality PPM": 720,
            "Audit Score": 86,
            "Complaint Rate %": 1.2,
            "Capacity Buffer %": 14,
            "Recyclability": 96,
            "Certification": 92,
            "Carbon Score": 88,
            "EPR Readiness": 94,
            "PCR Content %": 35,
            "Risk Category": "Low",
        },
        {
            "Supplier": "Regional Packworks",
            "Quoted Unit Price USD": 0.36,
            "Currency": "USD",
            "Unit": "piece",
            "MOQ": 15000,
            "Lead Time Days": 12,
            "Payment Terms": "Net 30",
            "Incoterms": "EXW",
            "OTIF %": 89,
            "Quality PPM": 1100,
            "Audit Score": 78,
            "Complaint Rate %": 2.1,
            "Capacity Buffer %": 10,
            "Recyclability": 85,
            "Certification": 76,
            "Carbon Score": 72,
            "EPR Readiness": 74,
            "PCR Content %": 18,
            "Risk Category": "Medium",
        },
        {
            "Supplier": "SecurePack Continuity Partners",
            "Quoted Unit Price USD": 0.47,
            "Currency": "USD",
            "Unit": "piece",
            "MOQ": 7500,
            "Lead Time Days": 9,
            "Payment Terms": "Net 60",
            "Incoterms": "DDP",
            "OTIF %": 98,
            "Quality PPM": 380,
            "Audit Score": 94,
            "Complaint Rate %": 0.4,
            "Capacity Buffer %": 28,
            "Recyclability": 91,
            "Certification": 95,
            "Carbon Score": 84,
            "EPR Readiness": 90,
            "PCR Content %": 28,
            "Risk Category": "Low",
        },
    ]
    return _append(base, rows)


def expand_flexible_laminates(base: pd.DataFrame, base_price: float) -> pd.DataFrame:
    common = base.iloc[0].to_dict()
    rows = [
        {
            **common,
            "Supplier": "Agile Converting Works",
            "Quoted Unit Price USD": round(base_price * 0.98, 3),
            "MOQ": 8000,
            "Lead Time Days": 14,
            "Payment Terms": "Net 30",
            "Incoterms": "DDP",
            "OTIF %": 92,
            "Quality PPM": 780,
            "Audit Score": 84,
            "Complaint Rate %": 1.4,
            "Capacity Buffer %": 12,
            "Supplier Capacity": 620000,
            "Recyclability": 66,
            "Certification": 84,
            "Carbon Score": 76,
            "EPR Readiness": 75,
            "Substrate Availability %": 74,
            "Press Capacity Utilisation %": 84,
            "Lamination Capacity Utilisation %": 86,
            "Printing Capability Score": 86,
            "Lamination Capability Score": 84,
            "Bond Strength Continuity Score": 80,
            "Seal Integrity Continuity Score": 79,
            "Solvent Retention Control Score": 82,
        },
        {
            **common,
            "Supplier": "Sustainable Barrier Converters",
            "Quoted Unit Price USD": round(base_price * 1.10, 3),
            "MOQ": 15000,
            "Lead Time Days": 20,
            "Payment Terms": "Net 60",
            "Incoterms": "DDP",
            "OTIF %": 96,
            "Quality PPM": 390,
            "Audit Score": 94,
            "Complaint Rate %": 0.5,
            "Capacity Buffer %": 20,
            "Supplier Capacity": 980000,
            "Recyclability": 78,
            "Certification": 96,
            "Carbon Score": 90,
            "EPR Readiness": 94,
            "Substrate Availability %": 88,
            "Press Capacity Utilisation %": 72,
            "Lamination Capacity Utilisation %": 74,
            "Printing Capability Score": 94,
            "Lamination Capability Score": 93,
            "Bond Strength Continuity Score": 94,
            "Seal Integrity Continuity Score": 93,
            "Solvent Retention Control Score": 95,
        },
        {
            **common,
            "Supplier": "ValueFlex Imports",
            "Quoted Unit Price USD": round(base_price * 0.90, 3),
            "MOQ": 60000,
            "Lead Time Days": 48,
            "Payment Terms": "Advance 30%",
            "Incoterms": "FOB",
            "OTIF %": 80,
            "Quality PPM": 1900,
            "Audit Score": 68,
            "Complaint Rate %": 4.2,
            "Capacity Buffer %": 4,
            "Supplier Capacity": 1400000,
            "Recyclability": 45,
            "Certification": 62,
            "Carbon Score": 58,
            "EPR Readiness": 55,
            "Substrate Availability %": 52,
            "Press Capacity Utilisation %": 96,
            "Lamination Capacity Utilisation %": 97,
            "Printing Capability Score": 69,
            "Lamination Capability Score": 66,
            "Bond Strength Continuity Score": 58,
            "Seal Integrity Continuity Score": 56,
            "Solvent Retention Control Score": 60,
            "Application Approval Status": "Conditional",
        },
    ]
    return _append(base, rows)


def expand_kraft_paper(base: pd.DataFrame) -> pd.DataFrame:
    rows = [
        {
            "Supplier": "Deccan Recycled Fibre Co",
            "Material": "Kraft Paper",
            "Kraft Variant": "Recycled Kraft",
            "GSM": 150,
            "Strength Grade": "22 BF",
            "Quoted Unit Price USD": 0.82,
            "Currency": "USD",
            "Unit": "kg",
            "MOQ": 18000,
            "Lead Time Days": 12,
            "Payment Terms": "Net 45",
            "Incoterms": "DDP",
            "OTIF %": 93,
            "Quality PPM": 760,
            "Audit Score": 85,
            "Complaint Rate %": 1.3,
            "Capacity Buffer %": 16,
            "Supplier Capacity": 680000,
            "Commodity Volatility %": 15,
            "Import Dependency %": 3,
            "Supplier Concentration %": 34,
            "Substitute Available": "Yes",
            "Duty %": 0,
            "Recyclability": 97,
            "Certification": 86,
            "Carbon Score": 84,
            "EPR Readiness": 88,
            "PCR Content %": 94,
            "Mill Allocation %": 74,
            "Moisture %": 7.8,
            "Fibre Availability %": 76,
            "Quality Continuity Score": 84,
            "Corrugated Linkage": "Approved demonstration assumption",
        },
        {
            "Supplier": "Eastern Virgin Kraft Mills",
            "Material": "Kraft Paper",
            "Kraft Variant": "Virgin Kraft",
            "GSM": 150,
            "Strength Grade": "22 BF",
            "Quoted Unit Price USD": 1.02,
            "Currency": "USD",
            "Unit": "kg",
            "MOQ": 30000,
            "Lead Time Days": 19,
            "Payment Terms": "Net 60",
            "Incoterms": "CIF",
            "OTIF %": 97,
            "Quality PPM": 340,
            "Audit Score": 94,
            "Complaint Rate %": 0.4,
            "Capacity Buffer %": 22,
            "Supplier Capacity": 1250000,
            "Commodity Volatility %": 20,
            "Import Dependency %": 30,
            "Supplier Concentration %": 44,
            "Substitute Available": "Yes",
            "Duty %": 3,
            "Recyclability": 91,
            "Certification": 95,
            "Carbon Score": 70,
            "EPR Readiness": 77,
            "PCR Content %": 0,
            "Mill Allocation %": 68,
            "Moisture %": 6.5,
            "Fibre Availability %": 92,
            "Quality Continuity Score": 95,
            "Corrugated Linkage": "Approved demonstration assumption",
        },
        {
            "Supplier": "Frontier Paper Traders",
            "Material": "Kraft Paper",
            "Kraft Variant": "Recycled Kraft",
            "GSM": 150,
            "Strength Grade": "22 BF",
            "Quoted Unit Price USD": 0.75,
            "Currency": "USD",
            "Unit": "kg",
            "MOQ": 65000,
            "Lead Time Days": 45,
            "Payment Terms": "Advance 30%",
            "Incoterms": "FOB",
            "OTIF %": 79,
            "Quality PPM": 2100,
            "Audit Score": 64,
            "Complaint Rate %": 4.8,
            "Capacity Buffer %": 3,
            "Supplier Capacity": 1450000,
            "Commodity Volatility %": 31,
            "Import Dependency %": 65,
            "Supplier Concentration %": 82,
            "Substitute Available": "No",
            "Duty %": 8,
            "Recyclability": 90,
            "Certification": 58,
            "Carbon Score": 62,
            "EPR Readiness": 57,
            "PCR Content %": 80,
            "Mill Allocation %": 98,
            "Moisture %": 10.5,
            "Fibre Availability %": 45,
            "Quality Continuity Score": 52,
            "Corrugated Linkage": "Conditional demonstration assumption",
        },
    ]
    return _append(base, rows)


def expand_steel(base: pd.DataFrame) -> pd.DataFrame:
    common = base.iloc[0].to_dict()
    rows = [
        {
            **common,
            "Supplier": "Western Integrated Steel",
            "Quoted Unit Price": 1.04,
            "Currency": "USD",
            "Quotation Currency": "USD",
            "Quoted Unit Price USD": 1.04,
            "MOQ": 22000,
            "Lead Time Days": 16,
            "Payment Terms": "Net 45",
            "Incoterms": "DDP",
            "OTIF %": 93,
            "Quality PPM": 700,
            "Audit Score": 86,
            "Complaint Rate %": 1.1,
            "Capacity Buffer %": 16,
            "Supplier Capacity": 1650000,
            "Capacity Utilisation %": 82,
            "Mill Allocation %": 78,
            "Import Dependency %": 8,
            "Supplier Concentration %": 42,
            "Quality Continuity Score": 85,
            "Risk Category": "Medium",
            "Eligibility Design Intent": "Eligible value supplier with moderate capacity pressure",
        },
        {
            **common,
            "Supplier": "Reliance Coated Coil Services",
            "Quoted Unit Price": 101.50,
            "Currency": "INR",
            "Quotation Currency": "INR",
            "Quoted Unit Price USD": None,
            "MOQ": 12000,
            "Lead Time Days": 10,
            "Payment Terms": "Net 60",
            "Incoterms": "DDP",
            "OTIF %": 98,
            "Quality PPM": 300,
            "Audit Score": 96,
            "Complaint Rate %": 0.3,
            "Capacity Buffer %": 30,
            "Supplier Capacity": 1200000,
            "Capacity Utilisation %": 61,
            "Mill Allocation %": 58,
            "Import Dependency %": 2,
            "Supplier Concentration %": 24,
            "Quality Continuity Score": 97,
            "Risk Category": "Low",
            "Eligibility Design Intent": "Eligible premium continuity supplier",
        },
        {
            **common,
            "Supplier": "EastAsia Coil Exports",
            "Quoted Unit Price": 0.95,
            "Currency": "USD",
            "Quotation Currency": "USD",
            "Quoted Unit Price USD": 0.95,
            "MOQ": 70000,
            "Lead Time Days": 55,
            "Payment Terms": "Advance 40%",
            "Incoterms": "FOB",
            "OTIF %": 78,
            "Quality PPM": 2200,
            "Audit Score": 61,
            "Complaint Rate %": 5.0,
            "Capacity Buffer %": 2,
            "Supplier Capacity": 2500000,
            "Capacity Utilisation %": 98,
            "Mill Allocation %": 99,
            "Import Dependency %": 100,
            "Supplier Concentration %": 88,
            "Quality Continuity Score": 48,
            "Risk Category": "High",
            "Supplier or Mill Approval": "Not approved",
            "Application Approval": "Not approved",
            "Test Certificate Availability": "Unavailable",
            "Paint Line Capability": "No",
            "Zinc Capability Max g/m²": 80,
            "Coil Weight Min MT": 18,
            "Coil Weight Max MT": 28,
            "Eligibility Design Intent": "Low-price technically ineligible supplier",
        },
    ]
    return _append(base, rows)
